name: Pinspector
version: "${version}"
description: "PersistentDataContainer(PDC) inspector"
api-version: 1.21
main: dev.krysztal.pinspector.Plugin
libraries:
    - "io.vavr:vavr:0.10.6"
    - "one.util:streamex:0.8.3"
