name: Gradle Package

on: ["push"]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  server-id: github
                  settings-path: ${{ github.workspace }}

            - name: Build with Gradle
              run: ./gradlew build

            - name: Publish to Modrinth
              run: ./gradlew publishModrinth --stacktrace
              env:
                  GH_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}

            - name: Publish to Hanger
              run: ./gradlew publishAllPublications --stacktrace
              env:
                  HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
